In [1]:
import pandas as pd

In [2]:
bookings_df = pd.read_csv('/content/bookings.csv')

In [3]:
bookings_df.head(23)

,ground_name,id,user_id,ground_id,slot_id,extra,date,app_name,payment_TxId,payment_TxRefNo,...,payment_signature,created_at,updated_at,timing_id,amount,is_cancel,contact_name,contact_number,username,phone
0,VB Cricket Club (V.B.C.C) 2,20,14,2,5,NaN,10/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-19 12:09:40,2017-04-19 12:09:40,1,1.0,0,NaN,NaN,Ajay kumar,7288855445
1,VB Cricket Club (V.B.C.C) 2,21,14,2,8,NaN,21/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 05:27:17,2017-04-21 05:27:17,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
2,VB Cricket Club (V.B.C.C) 2,22,14,2,8,NaN,20/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 05:27:32,2017-04-21 05:27:32,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
3,VB Cricket Club (V.B.C.C) 2,23,14,2,8,NaN,22/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 05:27:49,2017-04-21 05:27:49,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
4,VB Cricket Club (V.B.C.C) 2,24,14,2,7,NaN,23/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 05:28:50,2017-04-21 05:28:50,3,1.0,0,NaN,NaN,Ajay kumar,7288855445
5,VB Cricket Club (V.B.C.C) 2,25,14,2,8,NaN,26/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 06:34:39,2017-04-21 06:34:39,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
6,VB Cricket Club (V.B.C.C) 2,26,14,2,8,NaN,27/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 06:41:58,2017-04-21 06:41:58,4,10000.0,0,NaN,NaN,Ajay kumar,7288855445
7,VB Cricket Club (V.B.C.C) 2,27,14,2,8,NaN,28/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 06:45:38,2017-04-21 06:45:38,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
8,VB Cricket Club (V.B.C.C) 2,28,14,2,8,NaN,24/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 06:52:07,2017-04-21 06:52:07,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
9,VB Cricket Club (V.B.C.C),29,14,1,4,NaN,22/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 06:53:10,2017-04-21 06:53:10,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
10,VB Cricket Club (V.B.C.C),30,14,1,4,NaN,23/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 08:47:26,2017-04-21 08:47:26,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
11,VB Cricket Club (V.B.C.C),31,14,1,4,NaN,25/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 08:55:49,2017-04-21 08:55:49,4,1.0,0,NaN,NaN,Ajay kumar,7288855445
12,VB Cricket Club (V.B.C.C),32,14,1,2,NaN,26/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 10:12:59,2017-04-21 10:12:59,2,1.0,0,NaN,NaN,Ajay kumar,7288855445
13,VB Cricket Club (V.B.C.C),33,14,1,1,NaN,26/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 10:15:45,2017-04-21 10:15:45,1,1.0,0,NaN,NaN,Ajay kumar,7288855445
14,VB Cricket Club (V.B.C.C),34,14,1,3,NaN,26/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 10:18:33,2017-04-21 10:18:33,3,1.0,0,NaN,NaN,Ajay kumar,7288855445
15,VB Cricket Club (V.B.C.C) 2,35,14,2,6,NaN,29/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 12:12:49,2017-04-21 12:12:49,2,4000.0,0,NaN,NaN,Ajay kumar,7288855445
16,VB Cricket Club (V.B.C.C) 2,36,14,2,6,NaN,17/05/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 12:12:52,2017-04-21 12:12:52,2,1.0,0,NaN,NaN,Ajay kumar,7288855445
17,VB Cricket Club (V.B.C.C) 2,37,14,2,7,NaN,21/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-21 12:19:29,2017-04-21 12:19:29,3,4000.0,0,NaN,NaN,Ajay kumar,7288855445
18,VB Cricket Club (V.B.C.C) 2,38,14,2,6,NaN,25/04/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-22 04:35:23,2017-04-22 04:35:23,2,1.0,0,NaN,NaN,Ajay kumar,7288855445
19,VB Cricket Club (V.B.C.C),39,14,1,3,NaN,10/05/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-22 04:35:47,2017-04-22 04:35:47,3,1.0,0,NaN,NaN,Ajay kumar,7288855445
20,VB Cricket Club (V.B.C.C) 2,40,14,2,7,NaN,17/05/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-22 06:13:37,2017-04-22 06:13:37,3,1.0,0,NaN,NaN,Ajay kumar,7288855445
21,VB Cricket Club (V.B.C.C) 2,41,14,2,6,NaN,06/05/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-22 06:36:12,2017-04-22 06:36:12,2,1.0,0,NaN,NaN,Ajay kumar,7288855445
22,VB Cricket Club (V.B.C.C) 2,42,14,2,6,NaN,10/05/2017,NaN,OWNER,OWNER,...,OWNER,2017-04-24 10:22:12,2017-04-24 10:22:12,2,1.0,0,NaN,NaN,Ajay kumar,7288855445

In [4]:
bookings_df_filled = bookings_df.fillna('N/A')

In [5]:
bookings_df_cleaned = bookings_df_filled.drop(columns=bookings_df_filled.columns[bookings_df_filled.eq("N/A").all()])

In [6]:
bookings_df_cleaned.head(23)

,ground_name,id,user_id,ground_id,slot_id,date,app_name,payment_TxId,payment_TxRefNo,payment_pgTxnNo,...,payment_signature,created_at,updated_at,timing_id,amount,is_cancel,contact_name,contact_number,username,phone
0,VB Cricket Club (V.B.C.C) 2,20,14,2,5,10/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-19 12:09:40,2017-04-19 12:09:40,1,1.0,0,N/A,N/A,Ajay kumar,7288855445
1,VB Cricket Club (V.B.C.C) 2,21,14,2,8,21/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:27:17,2017-04-21 05:27:17,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
2,VB Cricket Club (V.B.C.C) 2,22,14,2,8,20/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:27:32,2017-04-21 05:27:32,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
3,VB Cricket Club (V.B.C.C) 2,23,14,2,8,22/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:27:49,2017-04-21 05:27:49,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
4,VB Cricket Club (V.B.C.C) 2,24,14,2,7,23/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:28:50,2017-04-21 05:28:50,3,1.0,0,N/A,N/A,Ajay kumar,7288855445
5,VB Cricket Club (V.B.C.C) 2,25,14,2,8,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:34:39,2017-04-21 06:34:39,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
6,VB Cricket Club (V.B.C.C) 2,26,14,2,8,27/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:41:58,2017-04-21 06:41:58,4,10000.0,0,N/A,N/A,Ajay kumar,7288855445
7,VB Cricket Club (V.B.C.C) 2,27,14,2,8,28/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:45:38,2017-04-21 06:45:38,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
8,VB Cricket Club (V.B.C.C) 2,28,14,2,8,24/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:52:07,2017-04-21 06:52:07,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
9,VB Cricket Club (V.B.C.C),29,14,1,4,22/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:53:10,2017-04-21 06:53:10,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
10,VB Cricket Club (V.B.C.C),30,14,1,4,23/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 08:47:26,2017-04-21 08:47:26,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
11,VB Cricket Club (V.B.C.C),31,14,1,4,25/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 08:55:49,2017-04-21 08:55:49,4,1.0,0,N/A,N/A,Ajay kumar,7288855445
12,VB Cricket Club (V.B.C.C),32,14,1,2,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 10:12:59,2017-04-21 10:12:59,2,1.0,0,N/A,N/A,Ajay kumar,7288855445
13,VB Cricket Club (V.B.C.C),33,14,1,1,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 10:15:45,2017-04-21 10:15:45,1,1.0,0,N/A,N/A,Ajay kumar,7288855445
14,VB Cricket Club (V.B.C.C),34,14,1,3,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 10:18:33,2017-04-21 10:18:33,3,1.0,0,N/A,N/A,Ajay kumar,7288855445
15,VB Cricket Club (V.B.C.C) 2,35,14,2,6,29/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 12:12:49,2017-04-21 12:12:49,2,4000.0,0,N/A,N/A,Ajay kumar,7288855445
16,VB Cricket Club (V.B.C.C) 2,36,14,2,6,17/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 12:12:52,2017-04-21 12:12:52,2,1.0,0,N/A,N/A,Ajay kumar,7288855445
17,VB Cricket Club (V.B.C.C) 2,37,14,2,7,21/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 12:19:29,2017-04-21 12:19:29,3,4000.0,0,N/A,N/A,Ajay kumar,7288855445
18,VB Cricket Club (V.B.C.C) 2,38,14,2,6,25/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 04:35:23,2017-04-22 04:35:23,2,1.0,0,N/A,N/A,Ajay kumar,7288855445
19,VB Cricket Club (V.B.C.C),39,14,1,3,10/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 04:35:47,2017-04-22 04:35:47,3,1.0,0,N/A,N/A,Ajay kumar,7288855445
20,VB Cricket Club (V.B.C.C) 2,40,14,2,7,17/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 06:13:37,2017-04-22 06:13:37,3,1.0,0,N/A,N/A,Ajay kumar,7288855445
21,VB Cricket Club (V.B.C.C) 2,41,14,2,6,06/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 06:36:12,2017-04-22 06:36:12,2,1.0,0,N/A,N/A,Ajay kumar,7288855445
22,VB Cricket Club (V.B.C.C) 2,42,14,2,6,10/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-24 10:22:12,2017-04-24 10:22:12,2,1.0,0,N/A,N/A,Ajay kumar,7288855445

In [7]:
import numpy as np

In [8]:
random_amounts = np.random.choice(range(600, 4001, 100), size=bookings_df_cleaned.shape[0])

In [9]:
bookings_df_cleaned['amount'] = random_amounts

In [10]:
bookings_df_cleaned.head(23)

,ground_name,id,user_id,ground_id,slot_id,date,app_name,payment_TxId,payment_TxRefNo,payment_pgTxnNo,...,payment_signature,created_at,updated_at,timing_id,amount,is_cancel,contact_name,contact_number,username,phone
0,VB Cricket Club (V.B.C.C) 2,20,14,2,5,10/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-19 12:09:40,2017-04-19 12:09:40,1,1200,0,N/A,N/A,Ajay kumar,7288855445
1,VB Cricket Club (V.B.C.C) 2,21,14,2,8,21/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:27:17,2017-04-21 05:27:17,4,600,0,N/A,N/A,Ajay kumar,7288855445
2,VB Cricket Club (V.B.C.C) 2,22,14,2,8,20/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:27:32,2017-04-21 05:27:32,4,800,0,N/A,N/A,Ajay kumar,7288855445
3,VB Cricket Club (V.B.C.C) 2,23,14,2,8,22/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:27:49,2017-04-21 05:27:49,4,2400,0,N/A,N/A,Ajay kumar,7288855445
4,VB Cricket Club (V.B.C.C) 2,24,14,2,7,23/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 05:28:50,2017-04-21 05:28:50,3,1300,0,N/A,N/A,Ajay kumar,7288855445
5,VB Cricket Club (V.B.C.C) 2,25,14,2,8,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:34:39,2017-04-21 06:34:39,4,2200,0,N/A,N/A,Ajay kumar,7288855445
6,VB Cricket Club (V.B.C.C) 2,26,14,2,8,27/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:41:58,2017-04-21 06:41:58,4,3500,0,N/A,N/A,Ajay kumar,7288855445
7,VB Cricket Club (V.B.C.C) 2,27,14,2,8,28/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:45:38,2017-04-21 06:45:38,4,1200,0,N/A,N/A,Ajay kumar,7288855445
8,VB Cricket Club (V.B.C.C) 2,28,14,2,8,24/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:52:07,2017-04-21 06:52:07,4,1200,0,N/A,N/A,Ajay kumar,7288855445
9,VB Cricket Club (V.B.C.C),29,14,1,4,22/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 06:53:10,2017-04-21 06:53:10,4,3900,0,N/A,N/A,Ajay kumar,7288855445
10,VB Cricket Club (V.B.C.C),30,14,1,4,23/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 08:47:26,2017-04-21 08:47:26,4,3400,0,N/A,N/A,Ajay kumar,7288855445
11,VB Cricket Club (V.B.C.C),31,14,1,4,25/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 08:55:49,2017-04-21 08:55:49,4,2400,0,N/A,N/A,Ajay kumar,7288855445
12,VB Cricket Club (V.B.C.C),32,14,1,2,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 10:12:59,2017-04-21 10:12:59,2,1200,0,N/A,N/A,Ajay kumar,7288855445
13,VB Cricket Club (V.B.C.C),33,14,1,1,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 10:15:45,2017-04-21 10:15:45,1,600,0,N/A,N/A,Ajay kumar,7288855445
14,VB Cricket Club (V.B.C.C),34,14,1,3,26/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 10:18:33,2017-04-21 10:18:33,3,2600,0,N/A,N/A,Ajay kumar,7288855445
15,VB Cricket Club (V.B.C.C) 2,35,14,2,6,29/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 12:12:49,2017-04-21 12:12:49,2,2200,0,N/A,N/A,Ajay kumar,7288855445
16,VB Cricket Club (V.B.C.C) 2,36,14,2,6,17/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 12:12:52,2017-04-21 12:12:52,2,1400,0,N/A,N/A,Ajay kumar,7288855445
17,VB Cricket Club (V.B.C.C) 2,37,14,2,7,21/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-21 12:19:29,2017-04-21 12:19:29,3,1300,0,N/A,N/A,Ajay kumar,7288855445
18,VB Cricket Club (V.B.C.C) 2,38,14,2,6,25/04/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 04:35:23,2017-04-22 04:35:23,2,3300,0,N/A,N/A,Ajay kumar,7288855445
19,VB Cricket Club (V.B.C.C),39,14,1,3,10/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 04:35:47,2017-04-22 04:35:47,3,2600,0,N/A,N/A,Ajay kumar,7288855445
20,VB Cricket Club (V.B.C.C) 2,40,14,2,7,17/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 06:13:37,2017-04-22 06:13:37,3,800,0,N/A,N/A,Ajay kumar,7288855445
21,VB Cricket Club (V.B.C.C) 2,41,14,2,6,06/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-22 06:36:12,2017-04-22 06:36:12,2,2300,0,N/A,N/A,Ajay kumar,7288855445
22,VB Cricket Club (V.B.C.C) 2,42,14,2,6,10/05/2017,N/A,OWNER,OWNER,OWNER,...,OWNER,2017-04-24 10:22:12,2017-04-24 10:22:12,2,1300,0,N/A,N/A,Ajay kumar,7288855445

In [11]:
!pip install fpdf

Collecting fpdf
  Downloading fpdf-1.7.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: fpdf
  Building wheel for fpdf (setup.py) ... done
  Created wheel for fpdf: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40704 sha256=59b3f5d331d8d8a94d0ec1ad89bebc17e43ccc91a59583791361548698595337
  Stored in directory: /root/.cache/pip/wheels/f9/95/ba/f418094659025eb9611f17cbcaf2334236bf39a0c3453ea455
Successfully built fpdf
Installing collected packages: fpdf
Successfully installed fpdf-1.7.2

In [12]:
from fpdf import FPDF

In [13]:
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Ground Bookings Data', 0, 1, 'C')

In [14]:
 def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

In [15]:
def df_to_pdf(dataframe):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    col_width = pdf.get_string_width(max(dataframe.columns, key=lambda x: len(x))) + 6  # padding
    row_height = 10

    # Print header
    for col in dataframe.columns:
        pdf.cell(col_width, row_height, col, border=1)
    pdf.ln(row_height)

    # Print rows
    for _, row in dataframe.iterrows():
        for item in row:
            pdf.cell(col_width, row_height, str(item), border=1)
        pdf.ln(row_height)

    return pdf

In [16]:
# Convert DataFrame to PDF
pdf_path = "bookings_updated_further_reduced.pdf"
pdf = df_to_pdf(bookings_df_cleaned)
pdf.output(pdf_path)

pdf_path

'bookings_updated_further_reduced.pdf'

In [17]:
# Remove the specified columns from the DataFrame
columns_to_remove = [
    "contact_name", "is_cancel", "contact_number", "updated_at", "created_at",
    "payment_signature", "payment_pgTxnNo", "app_name", "id", "user_id", "ground_id"
]
bookings_df_reduced = bookings_df_cleaned.drop(columns=columns_to_remove)

In [18]:
# Adjust the PDF generation function to reduce font size and layout in landscape mode
class PDF(FPDF):
    def __init__(self, orientation='L'):
        super().__init__(orientation=orientation)

    def header(self):
        self.set_font('Arial', 'B', 10)
        self.cell(0, 10, 'Ground Bookings Data', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

def df_to_pdf(dataframe):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    col_width = pdf.get_string_width(max(dataframe.columns, key=lambda x: len(x))) + 6  # padding
    row_height = 8
    pdf.set_font_size(8)

    # Print header
    for col in dataframe.columns:
        pdf.cell(col_width, row_height, col, border=1)
    pdf.ln(row_height)

    # Print rows
    for _, row in dataframe.iterrows():
        for item in row:
            pdf.cell(col_width, row_height, str(item), border=1)
        pdf.ln(row_height)

    return pdf

# Convert the reduced DataFrame to PDF
pdf_path_reduced = "bookings_updated_further_reduced.pdf"
pdf = df_to_pdf(bookings_df_reduced)
pdf.output(pdf_path_reduced)

pdf_path_reduced

'bookings_updated_further_reduced.pdf'

In [19]:
# Define the list of additional columns to remove
additional_columns_to_remove = ['column_name1', 'column_name2', 'column_name3']

# Remove valid columns from the DataFrame
valid_columns_to_remove = [col for col in additional_columns_to_remove if col in bookings_df_reduced.columns]
bookings_df_further_reduced = bookings_df_reduced.drop(columns=valid_columns_to_remove)

# Convert the further reduced DataFrame to PDF again
pdf_path_further_reduced = "bookings_updated_further_reduced.pdf"
pdf = df_to_pdf(bookings_df_further_reduced)
pdf.output(pdf_path_further_reduced)

pdf_path_further_reduced

'bookings_updated_further_reduced.pdf'

In [20]:
# Remove valid columns from the DataFrame
valid_columns_to_remove = [col for col in additional_columns_to_remove if col in bookings_df_reduced.columns]
bookings_df_further_reduced = bookings_df_reduced.drop(columns=valid_columns_to_remove)

# Convert the further reduced DataFrame to PDF
pdf_path_further_reduced = "bookings_updated_further_reduced.pdf"  # Specify the output PDF file path
pdf = df_to_pdf(bookings_df_further_reduced)
pdf.output(pdf_path_further_reduced)

print(f'PDF file "{pdf_path_further_reduced}" has been created successfully.')

PDF file "bookings_updated_further_reduced.pdf" has been created successfully.

In [21]:
# Remove the newly specified columns from the DataFrame
new_columns_to_remove = ["payment_issuerRefNo", "timing_id"]
bookings_df_final = bookings_df_further_reduced.drop(columns=new_columns_to_remove)

# Convert the final DataFrame to PDF
pdf_path_final = "/bookings_final.pdf"
pdf = df_to_pdf(bookings_df_final)
pdf.output(pdf_path_final)

pdf_path_final

'/bookings_final.pdf'

In [22]:
# Remove the newly specified columns from the DataFrame
new_columns_to_remove = ["payment_issuerRefNo", "timing_id"]
bookings_df_final = bookings_df_further_reduced.drop(columns=new_columns_to_remove)

# Convert the final DataFrame to PDF
pdf_path_final = "/content/bookings_updated_further_reduced.pdf"  # Specify the output PDF file path
pdf = df_to_pdf(bookings_df_final)
pdf.output(pdf_path_final)

# Access the final PDF file path
print(f'PDF file "{pdf_path_final}" has been created successfully.')

# You can now access the generated PDF at pdf_path_final

PDF file "/content/bookings_updated_further_reduced.pdf" has been created successfully.

In [23]:
def df_to_pdf_adjusted(dataframe):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Set custom width for the "ground_name" column
    ground_name_width = pdf.get_string_width(max(dataframe["ground_name"], key=lambda x: len(x))) + 6
    default_col_width = pdf.get_string_width(max(dataframe.columns, key=lambda x: len(x))) + 6  # padding
    row_height = 8
    pdf.set_font_size(8)

    # Print header
    for col in dataframe.columns:
        if col == "ground_name":
            pdf.cell(ground_name_width, row_height, col, border=1)
        else:
            pdf.cell(default_col_width, row_height, col, border=1)
    pdf.ln(row_height)

    # Print rows
    for _, row in dataframe.iterrows():
        for col, item in zip(dataframe.columns, row):
            if col == "ground_name":
                pdf.cell(ground_name_width, row_height, str(item), border=1)
            else:
                pdf.cell(default_col_width, row_height, str(item), border=1)
        pdf.ln(row_height)

    return pdf

# Convert the final DataFrame to PDF with adjusted column width
pdf_path_adjusted = "/content/bookings_updated_further_reduced.pdf"
pdf = df_to_pdf_adjusted(bookings_df_final)
pdf.output(pdf_path_adjusted)

pdf_path_adjusted

'/content/bookings_updated_further_reduced.pdf'

In [24]:
def df_to_pdf_final(dataframe):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Set custom width for the "ground_name" and "username" columns
    ground_name_width = pdf.get_string_width(max(dataframe["ground_name"], key=lambda x: len(x))) + 6
    username_width = pdf.get_string_width(max(dataframe["username"], key=lambda x: len(x))) + 6
    default_col_width = pdf.get_string_width(max(dataframe.columns, key=lambda x: len(x))) + 6  # padding
    row_height = 8
    pdf.set_font_size(8)

    # Print header
    for col in dataframe.columns:
        if col == "ground_name":
            pdf.cell(ground_name_width, row_height, col, border=1)
        elif col == "username":
            pdf.cell(username_width, row_height, col, border=1)
        else:
            pdf.cell(default_col_width, row_height, col, border=1)
    pdf.ln(row_height)

    # Print rows
    for _, row in dataframe.iterrows():
        for col, item in zip(dataframe.columns, row):
            if col == "ground_name":
                pdf.cell(ground_name_width, row_height, str(item), border=1)
            elif col == "username":
                pdf.cell(username_width, row_height, str(item), border=1)
            else:
                pdf.cell(default_col_width, row_height, str(item), border=1)
        pdf.ln(row_height)

    # Add summary data on the last page
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Summary Data', 0, 1, 'C')

    # Total unique booking by ground_name and their total amount
    summary_data = dataframe.groupby("ground_name").agg(
        total_bookings=pd.NamedAgg(column="amount", aggfunc="count"),
        total_amount=pd.NamedAgg(column="amount", aggfunc="sum")
    ).reset_index()

    pdf.set_font_size(10)
    pdf.ln(10)
    for _, row in summary_data.iterrows():
        pdf.cell(0, 10, f"Ground Name: {row['ground_name']}", ln=True)
        pdf.cell(0, 10, f"Total Bookings: {row['total_bookings']}", ln=True)
        pdf.cell(0, 10, f"Total Amount: {row['total_amount']}", ln=True)
        pdf.ln(10)

    # Total amount
    total_amount = dataframe["amount"].sum()
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Overall Total Amount: {total_amount}", 0, 1, 'C')

    return pdf

# Convert the final DataFrame to PDF with adjusted column width and summary data
pdf_path_final = "/content/bookings_updated_further_reduced.pdf"
pdf = df_to_pdf_final(bookings_df_final)
pdf.output(pdf_path_final)

pdf_path_final

'/content/bookings_updated_further_reduced.pdf'

In [25]:
def df_to_pdf_with_table_summary(dataframe):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Set custom width for the "ground_name" and "username" columns
    ground_name_width = pdf.get_string_width(max(dataframe["ground_name"], key=lambda x: len(x))) + 6
    username_width = pdf.get_string_width(max(dataframe["username"], key=lambda x: len(x))) + 6
    default_col_width = pdf.get_string_width(max(dataframe.columns, key=lambda x: len(x))) + 6  # padding
    row_height = 8
    pdf.set_font_size(8)

    # Print header
    for col in dataframe.columns:
        if col == "ground_name":
            pdf.cell(ground_name_width, row_height, col, border=1)
        elif col == "username":
            pdf.cell(username_width, row_height, col, border=1)
        else:
            pdf.cell(default_col_width, row_height, col, border=1)
    pdf.ln(row_height)

    # Print rows
    for _, row in dataframe.iterrows():
        for col, item in zip(dataframe.columns, row):
            if col == "ground_name":
                pdf.cell(ground_name_width, row_height, str(item), border=1)
            elif col == "username":
                pdf.cell(username_width, row_height, str(item), border=1)
            else:
                pdf.cell(default_col_width, row_height, str(item), border=1)
        pdf.ln(row_height)

    # Add summary data on the last page
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Summary Data', 0, 1, 'C')

    # Total unique booking by ground_name and their total amount
    summary_data = dataframe.groupby("ground_name").agg(
        total_bookings=pd.NamedAgg(column="amount", aggfunc="count"),
        total_amount=pd.NamedAgg(column="amount", aggfunc="sum")
    ).reset_index()

    pdf.set_font_size(10)
    pdf.ln(10)

    # Print header for summary table
    summary_headers = ["Ground Name", "Total Bookings", "Total Amount"]
    summary_col_widths = [
        pdf.get_string_width(max(summary_data["ground_name"], key=lambda x: len(x))) + 6,
        pdf.get_string_width(str(max(summary_data["total_bookings"]))) + 6,
        pdf.get_string_width(str(max(summary_data["total_amount"]))) + 6
    ]
    for header, col_width in zip(summary_headers, summary_col_widths):
        pdf.cell(col_width, row_height, header, border=1)
    pdf.ln(row_height)

    # Print rows for summary table
    for _, row in summary_data.iterrows():
        pdf.cell(summary_col_widths[0], row_height, str(row['ground_name']), border=1)
        pdf.cell(summary_col_widths[1], row_height, str(row['total_bookings']), border=1)
        pdf.cell(summary_col_widths[2], row_height, str(row['total_amount']), border=1)
        pdf.ln(row_height)

    # Total amount
    total_amount = dataframe["amount"].sum()
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Overall Total Amount: {total_amount}", 0, 1, 'C')

    return pdf

# Convert the final DataFrame to PDF with adjusted column width and tabular summary data
pdf_path_table_summary = "/content/bookings_table_fixed_summary.pdf"
pdf = df_to_pdf_with_table_summary(bookings_df_final)
pdf.output(pdf_path_table_summary)

pdf_path_table_summary

'/content/bookings_table_fixed_summary.pdf'

In [26]:
def df_to_pdf_with_fixed_table_summary(dataframe):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Set custom width for the "ground_name" and "username" columns
    ground_name_width = pdf.get_string_width(max(dataframe["ground_name"], key=lambda x: len(x))) + 6
    username_width = pdf.get_string_width(max(dataframe["username"], key=lambda x: len(x))) + 6
    default_col_width = pdf.get_string_width(max(dataframe.columns, key=lambda x: len(x))) + 6  # padding
    row_height = 8
    pdf.set_font_size(8)

    # Print header
    for col in dataframe.columns:
        if col == "ground_name":
            pdf.cell(ground_name_width, row_height, col, border=1)
        elif col == "username":
            pdf.cell(username_width, row_height, col, border=1)
        else:
            pdf.cell(default_col_width, row_height, col, border=1)
    pdf.ln(row_height)

    # Print rows
    for _, row in dataframe.iterrows():
        for col, item in zip(dataframe.columns, row):
            if col == "ground_name":
                pdf.cell(ground_name_width, row_height, str(item), border=1)
            elif col == "username":
                pdf.cell(username_width, row_height, str(item), border=1)
            else:
                pdf.cell(default_col_width, row_height, str(item), border=1)
        pdf.ln(row_height)

    # Add summary data on the last page
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Summary Data', 0, 1, 'C')

    # Total unique booking by ground_name and their total amount
    summary_data = dataframe.groupby("ground_name").agg(
        total_bookings=pd.NamedAgg(column="amount", aggfunc="count"),
        total_amount=pd.NamedAgg(column="amount", aggfunc="sum")
    ).reset_index()

    pdf.set_font_size(10)
    pdf.ln(10)

    # Print header for summary table
    summary_headers = ["Ground Name", "Total Bookings", "Total Amount (INR)"]
    summary_col_widths = [
        pdf.get_string_width(max(summary_data["ground_name"], key=lambda x: len(x))) + 6,
        pdf.get_string_width("Total Bookings") + 6,
        pdf.get_string_width("Total Amount (INR)") + 6
    ]
    for header, col_width in zip(summary_headers, summary_col_widths):
        pdf.cell(col_width, row_height, header, border=1)
    pdf.ln(row_height)

    # Print rows for summary table
    for _, row in summary_data.iterrows():
        pdf.cell(summary_col_widths[0], row_height, str(row['ground_name']), border=1)
        pdf.cell(summary_col_widths[1], row_height, str(row['total_bookings']), border=1)
        pdf.cell(summary_col_widths[2], row_height, f"INR {row['total_amount']}", border=1)
        pdf.ln(row_height)

    # Total amount
    total_amount = dataframe["amount"].sum()
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Overall Total Amount: INR {total_amount}", 0, 1, 'C')

    return pdf

# Convert the final DataFrame to PDF with fixed tabular summary data
pdf_path_table_fixed_summary = "/content/bookings_table_fixed_summary.pdf"
pdf = df_to_pdf_with_fixed_table_summary(bookings_df_final)
pdf.output(pdf_path_table_fixed_summary)

pdf_path_table_fixed_summary

'/content/bookings_table_fixed_summary.pdf'